### ISSUE TITLE
Broken github page for downloads.

### ISSUE THREAD

**Issue by DarkAlchy** [markwal/GpxUi#2]

**Comment by markwal** [comment]
Works for me.  The download link is on this page: http://markwal.github.io/GpxUi/

**Comment by DarkAlchy** [comment]
http://i.imgur.com/J654C9Q.jpg

What am I doing wrong?
--------------------------------------------
On Thu, 8/3/17, Mark Walker <notifications@github.com> wrote:

 Subject: Re: [markwal/GpxUi] Broken github page for downloads. (#2)
 To: "markwal/GpxUi" <GpxUi@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, August 3, 2017, 6:05 PM
 
 Works for me.  The download link
 is on this page: http://markwal.github.io/GpxUi/
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by markwal** [comment]
What link did you click on.  The page I linked above has two links one for Windows:

https://github.com/markwal/GpxUi/releases/download/2.5.2/setup.exe

And one for Mac:

https://github.com/markwal/GpxUi/releases/download/2.5.2/GpxUi.dmg

Neither of those is the xml file you're showing.

**Comment by DarkAlchy** [comment]
That first link so I just clicked it from your email and the same error.
--------------------------------------------
On Fri, 8/4/17, Mark Walker <notifications@github.com> wrote:

 Subject: Re: [markwal/GpxUi] Broken github page for downloads. (#2)
 To: "markwal/GpxUi" <GpxUi@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, August 4, 2017, 2:07 AM
 
 What link did you click on.  The
 page I linked above has two links one for Windows:
 https://github.com/markwal/GpxUi/releases/download/2.5.2/setup.exe
 And one for Mac:
 https://github.com/markwal/GpxUi/releases/download/2.5.2/GpxUi.dmg
 Neither of those is the xml file you're showing.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by markwal** [comment]
It looks like an error message from Amazon Web Services underneath Github.  Perhaps github is having an outage in your region?  Or maybe Firefox is doing something funny.

**Comment by markwal** [comment]
You may want to try to download a zip file from the release, just to test if it is related to the .exe:

https://github.com/markwal/GpxUi/releases/tag/2.5.2

Or try downloading a zip file from elsewhere on github.com:

https://github.com/foosel/OctoPrint/releases

**Comment by DarkAlchy** [comment]
The first link was the same error but the second link downloaded just fine.
--------------------------------------------
On Fri, 8/4/17, Mark Walker <notifications@github.com> wrote:

 Subject: Re: [markwal/GpxUi] Broken github page for downloads. (#2)
 To: "markwal/GpxUi" <GpxUi@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, August 4, 2017, 2:55 AM
 
 You may want to try to download a
 zip file from the release, just to test if it is related to
 the .exe:
 https://github.com/markwal/GpxUi/releases/tag/2.5.2
 Or try downloading a zip file from elsewhere on
 github.com:
 https://github.com/foosel/OctoPrint/releases
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by DarkAlchy** [comment]
Bingo, I redid the first link and grabbed the source code zip and it downloaded just fine so it is the .exe doing it.  Must be a safety measure from github or AWS.
--------------------------------------------
On Fri, 8/4/17, Mark Walker <notifications@github.com> wrote:

 Subject: Re: [markwal/GpxUi] Broken github page for downloads. (#2)
 To: "markwal/GpxUi" <GpxUi@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, August 4, 2017, 2:55 AM
 
 You may want to try to download a
 zip file from the release, just to test if it is related to
 the .exe:
 https://github.com/markwal/GpxUi/releases/tag/2.5.2
 Or try downloading a zip file from elsewhere on
 github.com:
 https://github.com/foosel/OctoPrint/releases
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by DarkAlchy** [comment]
With this revelation how do I get that exe?
--------------------------------------------
On Fri, 8/4/17, Mark Walker <notifications@github.com> wrote:

 Subject: Re: [markwal/GpxUi] Broken github page for downloads. (#2)
 To: "markwal/GpxUi" <GpxUi@noreply.github.com>
 Cc: "DarkAlchy" <darkprognosis@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Friday, August 4, 2017, 2:55 AM
 
 You may want to try to download a
 zip file from the release, just to test if it is related to
 the .exe:
 https://github.com/markwal/GpxUi/releases/tag/2.5.2
 Or try downloading a zip file from elsewhere on
 github.com:
 https://github.com/foosel/OctoPrint/releases
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
